trigger:
  - refs/tags/*
  - main
  - staging
  - master
  - develop

resources:
  repositories:
    - repository: SharedResources
      type: git
      name: Creative Design Scripts/0_Shared

variables:
  - name: tag
    value: $[replace(variables['Build.SourceBranch'], 'refs/tags/','')]

  - name: isTag
    value: $[eq(variables['Build.SourceBranch'], 'refs/tags/*')]

  - name: deployTarget
    ${{ if or(eq(variables['Build.SourceBranchName'], 'master'),eq(variables['Build.SourceBranchName'], 'main')) }}:
      value: production
    ${{ elseif or(eq(variables['Build.SourceBranchName'], 'preview'),eq(variables['Build.SourceBranchName'], 'staging')) }}:
      value: staging
    ${{ else }}:
      value: dev

pool:
  vmImage: windows-2019

stages:
  - stage: InstallDependencies
    jobs:
    - template: BuildAndPublishAzure.yml@SharedResources
      parameters:
        deploymentToken: $(deploymentToken)
        deployTarget: $(deployTarget)